import {chromium} from 'playwright';
const base=process.env.TEST_SITE||'http://127.0.0.1:8787';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
if(!process.env.TEST_SITE)await page.route('**/api/shared-data',route=>route.fulfill({json:{data:{}}}));
await page.goto(base+'/#dto');
await page.locator('#login-form input[name=username]').fill(process.env.TEST_USERNAME);
await page.locator('#login-form input[name=password]').fill(process.env.TEST_PASSWORD);
await page.locator('#login-form button[type=submit]').click();
await page.waitForFunction(()=>document.querySelector('#loginRoot')?.hidden===true,{},{timeout:30000});
await page.locator('[data-dto2-detail]').first().waitFor({timeout:30000});
await page.locator('[data-dto2-detail]').first().click();
await page.getByRole('button',{name:'Editar DTO',exact:true}).waitFor();
await page.getByRole('button',{name:'Excluir DTO',exact:true}).waitFor();
await page.getByRole('button',{name:'Editar DTO',exact:true}).click();
await page.locator('dialog[open] textarea[name=actionPlan]').waitFor();
if(!process.env.TEST_SITE){
 await page.locator('dialog textarea').fill('Correção de execução — teste local');
 await page.getByRole('button',{name:'Salvar DTO',exact:true}).click();
 await page.locator('.dto2-action').filter({hasText:'Correção de execução — teste local'}).waitFor();
 await page.reload();
 await page.locator('[data-dto2-detail]').first().click();
 await page.locator('.dto2-action').filter({hasText:'Correção de execução — teste local'}).waitFor();
 page.once('dialog',d=>d.accept());
 await page.getByRole('button',{name:'Excluir DTO',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('[data-dto2-detail]'));
}else await page.getByRole('button',{name:'Cancelar',exact:true}).click();
if(errors.length)throw Error(errors.join('\n'));
console.log('Browser login, DTO detail, Edit/Delete controls and editor verified');
await browser.close();
