import fs from 'node:fs/promises';
import path from 'node:path';
import vm from 'node:vm';
const config=await fs.readFile(path.join(process.env.APPDATA,'xdg.config/.wrangler/config/default.toml'),'utf8');
const token=config.match(/oauth_token\s*=\s*"([^"]+)"/)[1];
const response=await fetch('https://api.cloudflare.com/client/v4/accounts/a8ebe5f01fda0caad99981f68ec866b9/workers/scripts/lead-gestao/content/v2',{headers:{Authorization:`Bearer ${token}`}});
if(!response.ok)throw Error(`Download ${response.status}`);
const form=await response.formData();
const file=[...form.values()].find(value=>value.name==='index.js');
if(!file)throw Error('Missing module');
const code=await file.text();
const start=code.indexOf('var assets = new Map(');
const end=code.indexOf('\nvar auditActionSeed',start);
if(start<0||end<0)throw Error('Asset boundaries not found');
const declaration=code.slice(start,end);
const assets=vm.runInNewContext(declaration+'; assets',{}, {timeout:2000});
await fs.mkdir('recovered',{recursive:true});
await fs.writeFile('recovered/active-worker.js',code);
await fs.writeFile('recovered/assets.json',JSON.stringify([...assets.values()],null,2));
await fs.writeFile('recovered/runtime.js',code.slice(0,start)+'/* ASSET_MAP */\n'+code.slice(end));
console.log(JSON.stringify({assets:assets.size,bytes:Buffer.byteLength(code)}));
